export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const FEEDS_SEARCH = 'FEEDS_SEARCH';
export const FEEDS_SET = 'FEEDS_SET';
export const FEEDS_APPEND = 'FEEDS_APPEND';
export const FEEDS_UPDATE = 'FEEDS_UPDATE';
export const REACTIONS_SET = 'REACTIONS_SET';
export const REACTIONS_APPEND = 'REACTIONS_APPEND';
export const REACTION_DELETE = 'REACTION_DELETE';
export const ENTRYLIST_COMPETITION_VIDEO = 'ENTRYLIST_COMPETITION_VIDEO';
export const VIDEOS_SEARCH = 'VIDEOS_SEARCH';
export const MYVIDEOS_SEARCH = 'MYVIDEOS_SEARCH';
export const VIDEOS_SET = 'VIDEOS_SET';
export const VIDEOS_APPEND = 'VIDEOS_APPEND';
export const VIDEOS_UPDATE = 'VIDEOS_UPDATE';
export const VIDEOS_REACTIONS_SET = 'VIDEOS_REACTIONS_SET';
export const VIDEOS_REACTIONS_APPEND = 'VIDEOS_REACTIONS_APPEND';
export const VIDEO_ACTIVE = 'VIDEO_ACTIVE';
export const VIDEO_HOME_ACTIVE = 'VIDEO_HOME_ACTIVE';
export const MY_VIDEOS_ACTIVE = 'MY_VIDEOS_ACTIVE';
export const COMPETITION_VIDEO = "COMPETITION_VIDEO";
export const LOCAL_FEED_VIDEO = "LOCAL_FEED_VIDEO";
export const LOCAL_DELETED_VIDEO = "LOCAL_DELETED_VIDEO";
export const MY_COMPETITIONS_ACTIVE = 'MY_COMPETITIONS_ACTIVE';

export const KARAOKE_SEARCH = 'KARAOKE_SEARCH';
export const DOOP_SEARCH = 'DOOP_SEARCH';

export const TOGGLE_SOUND = 'TOGGLE_SOUND';

export const SOCIAL_APPEND_FOLLOWERS = 'SOCIAL_APPEND_FOLLOWERS';
export const SOCIAL_APPEND_FOLLOWING = 'SOCIAL_APPEND_FOLLOWING';
export const SOCIAL_APPEND_BLOCKS = 'SOCIAL_APPEND_BLOCKS';
export const SOCIAL_APPEND_BLOCKERS = 'SOCIAL_APPEND_BLOCKERS';
export const SET_BLOCK_USER = 'SET_BLOCK_USER';
export const SETTINGS_SHOW_PROMO = 'SETTINGS_SHOW_PROMO';
export const SETTINGS_INITIAL = 'SETTINGS_INITIAL';
export const SETTINGS_UPGRADE = 'SETTINGS_UPGRADE';

export const RESET_ACTION = 'RESET_ACTION';
export const COMPETITION_VIDEO_ACTIVE='COMPETITION_VIDEO_ACTIVE';
export const SUCCESS_VIDEO='SUCCESS_VIDEO';
