#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#require_relative '../node_modules/react-native/scripts/react_native_pods'
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")

platform :ios, '13.0'

target 'Vayy Up' do
  pod 'react-native-ffmpeg/https-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
  use_unimodules!
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  
end

